### ISSUE TITLE
What file do we need to enter?

### ISSUE THREAD

**Issue by ghost** [FireyFly/webshark#1]
I was excited to find there was a packet visualizer but after reading the `README` I am still confused on how to use it, especially in relation to `WireShark`. Would somebody mind clarifying this for me>

**Comment by FireyFly** [comment]
Hi! I wrote this code as a utility for a reversing project I was working on back in 2014, and haven't really worked on it since then, so a lot about this project/tool isn't great for actual practical use. (that is, the UI could use a lot of improvements and polishing, etc.) So, I'm not sure I'd really recommend using it as is--I think this is mostly useful as a starting point/inspiration at this point.

That said, if you really do want to use it, I don't mind clarifying. If you use Wireshark to do a package capture, you can save the captured packages as a .pcapng or .pcap file.  This tool lets you view a .pcap capture in a timeline view as the screenshot shows (with a box representing a packet, and the length of the box being indicative of the packet length).

That is, the file you're asked to browse for is the .pcap packet dump that you want to look at/visualize. (note that .pcapng isn't supported, but as indicated in the README you can use the `editcap` command from Wireshark to convert a .pcapng to .pcap)
